version: '3.8'

services:
  flinza-cluster:
    build: .
    container_name: flinza_lead_cluster
    restart: always
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4096M
    command: python -u launch_cluster.py
