# DTC Brand Registry & Sources curated for Flinza Works ICP
# Categories: Fashion & Apparel, Fashion Accessories, Jewelry, Health & Supplements, Skincare & Extended DTC
# Size: 1-100 employees, $0-10M rev, US/UK/CA/AU/EU

TARGET_BRANDS = [
    # --- FASHION & APPAREL: Streetwear, Athleisure, Denim, Swimwear, Casual ---
    {"brand": "Cuts Clothing", "domain": "cutsclothing.com", "niche": "Fashion & Apparel", "sub_niche": "Casual / Athleisure", "country": "United States", "employee_est": "11-50"},
    {"brand": "True Classic", "domain": "trueclassictees.com", "niche": "Fashion & Apparel", "sub_niche": "Everyday Wear", "country": "United States", "employee_est": "51-100"},
    {"brand": "Vuori", "domain": "vuoriclothing.com", "niche": "Fashion & Apparel", "sub_niche": "Athleisure", "country": "United States", "employee_est": "51-100"},
    {"brand": "Represent Clo", "domain": "representclo.com", "niche": "Fashion & Apparel", "sub_niche": "Streetwear", "country": "United Kingdom", "employee_est": "11-50"},
    {"brand": "Cole Buxton", "domain": "colebuxton.com", "niche": "Fashion & Apparel", "sub_niche": "Streetwear", "country": "United Kingdom", "employee_est": "11-50"},
    {"brand": "Chubbies", "domain": "chubbiesshorts.com", "niche": "Fashion & Apparel", "sub_niche": "Swimwear / Casual", "country": "United States", "employee_est": "51-100"},
    {"brand": "Mugsy Jeans", "domain": "mugsyjeans.com", "niche": "Fashion & Apparel", "sub_niche": "Denim", "country": "United States", "employee_est": "11-50"},
    {"brand": "Ten Thousand", "domain": "tenthousand.cc", "niche": "Fashion & Apparel", "sub_niche": "Activewear", "country": "United States", "employee_est": "11-50"},
    {"brand": "Outerknown", "domain": "outerknown.com", "niche": "Fashion & Apparel", "sub_niche": "Eco-friendly Outerwear", "country": "United States", "employee_est": "11-50"},
    {"brand": "Bylt Basics", "domain": "byltbasics.com", "niche": "Fashion & Apparel", "sub_niche": "Basics & Athleisure", "country": "United States", "employee_est": "11-50"},
    {"brand": "Rhone", "domain": "rhone.com", "niche": "Fashion & Apparel", "sub_niche": "Athleisure & Performance", "country": "United States", "employee_est": "51-100"},
    {"brand": "Barbell Apparel", "domain": "barbellapparel.com", "niche": "Fashion & Apparel", "sub_niche": "Athleisure & Denim", "country": "United States", "employee_est": "11-50"},
    {"brand": "Western Rise", "domain": "westernrise.com", "niche": "Fashion & Apparel", "sub_niche": "Performance Outerwear", "country": "United States", "employee_est": "1-10"},
    {"brand": "Public Rec", "domain": "publicrec.com", "niche": "Fashion & Apparel", "sub_niche": "Loungewear & Casual", "country": "United States", "employee_est": "11-50"},
    {"brand": "Birdwell Beach Britches", "domain": "birdwell.com", "niche": "Fashion & Apparel", "sub_niche": "Swimwear", "country": "United States", "employee_est": "11-50"},
    {"brand": "Fair Harbor", "domain": "fairharborclothing.com", "niche": "Fashion & Apparel", "sub_niche": "Sustainable Swimwear", "country": "United States", "employee_est": "11-50"},
    {"brand": "Ksubi", "domain": "ksubi.com", "niche": "Fashion & Apparel", "sub_niche": "Denim & Streetwear", "country": "Australia", "employee_est": "11-50"},
    {"brand": "Venroy", "domain": "venroy.com.au", "niche": "Fashion & Apparel", "sub_niche": "Leisure & Resortwear", "country": "Australia", "employee_est": "11-50"},
    {"brand": "Lorna Jane", "domain": "lornajane.com", "niche": "Fashion & Apparel", "sub_niche": "Activewear", "country": "Australia", "employee_est": "51-100"},
    {"brand": "Dope Snow", "domain": "dopesnow.com", "niche": "Fashion & Apparel", "sub_niche": "Outdoor & Snowwear", "country": "Sweden", "employee_est": "11-50"},
    {"brand": "Monte Carlo Streetwear", "domain": "montecwear.com", "niche": "Fashion & Apparel", "sub_niche": "Outerwear & Streetwear", "country": "Sweden", "employee_est": "11-50"},
    {"brand": "Girlfriend Collective", "domain": "girlfriend.com", "niche": "Fashion & Apparel", "sub_niche": "Sustainable Athleisure", "country": "United States", "employee_est": "11-50"},
    {"brand": "Parade", "domain": "yourparade.com", "niche": "Fashion & Apparel", "sub_niche": "Underwear & Loungewear", "country": "United States", "employee_est": "11-50"},
    {"brand": "TomboyX", "domain": "tomboyx.com", "niche": "Fashion & Apparel", "sub_niche": "Inclusive Underwear", "country": "United States", "employee_est": "11-50"},
    {"brand": "Summersalt", "domain": "summersalt.com", "niche": "Fashion & Apparel", "sub_niche": "Swimwear & Resortwear", "country": "United States", "employee_est": "11-50"},
    {"brand": "Andie Swim", "domain": "andieswim.com", "niche": "Fashion & Apparel", "sub_niche": "Swimwear", "country": "United States", "employee_est": "11-50"},
    {"brand": "Tentree", "domain": "tentree.com", "niche": "Fashion & Apparel", "sub_niche": "Eco Casual", "country": "Canada", "employee_est": "51-100"},
    {"brand": "Kotn", "domain": "kotn.com", "niche": "Fashion & Apparel", "sub_niche": "Ethical Basics", "country": "Canada", "employee_est": "11-50"},
    {"brand": "Reigning Champ", "domain": "reigningchamp.com", "niche": "Fashion & Apparel", "sub_niche": "Premium Athleisure", "country": "Canada", "employee_est": "11-50"},
    {"brand": "Naked & Famous Denim", "domain": "nakedandfamousdenim.com", "niche": "Fashion & Apparel", "sub_niche": "Raw Denim", "country": "Canada", "employee_est": "11-50"},

    # --- FASHION ACCESSORIES: Hats, Bags, Sunglasses, Belts, Watches, Wallets ---
    {"brand": "Bellroy", "domain": "bellroy.com", "niche": "Fashion Accessories", "sub_niche": "Wallets & Bags", "country": "Australia", "employee_est": "51-100"},
    {"brand": "The Ridge", "domain": "ridge.com", "niche": "Fashion Accessories", "sub_niche": "Wallets & EDC", "country": "United States", "employee_est": "51-100"},
    {"brand": "Dagne Dover", "domain": "dagnedover.com", "niche": "Fashion Accessories", "sub_niche": "Bags & Backpacks", "country": "United States", "employee_est": "11-50"},
    {"brand": "Beis Travel", "domain": "beistravel.com", "niche": "Fashion Accessories", "sub_niche": "Luggage & Bags", "country": "United States", "employee_est": "11-50"},
    {"brand": "Calpak", "domain": "calpaktravel.com", "niche": "Fashion Accessories", "sub_niche": "Travel Bags", "country": "United States", "employee_est": "11-50"},
    {"brand": "Monos", "domain": "monos.com", "niche": "Fashion Accessories", "sub_niche": "Luggage & Bags", "country": "Canada", "employee_est": "11-50"},
    {"brand": "July Luggage", "domain": "july.com", "niche": "Fashion Accessories", "sub_niche": "Travel & Bags", "country": "Australia", "employee_est": "11-50"},
    {"brand": "MVMT", "domain": "mvmt.com", "niche": "Fashion Accessories", "sub_niche": "Watches & Eyewear", "country": "United States", "employee_est": "11-50"},
    {"brand": "Blenders Eyewear", "domain": "blenderseyewear.com", "niche": "Fashion Accessories", "sub_niche": "Sunglasses & Eyewear", "country": "United States", "employee_est": "51-100"},
    {"brand": "Goodr", "domain": "goodr.com", "niche": "Fashion Accessories", "sub_niche": "Active Sunglasses", "country": "United States", "employee_est": "51-100"},
    {"brand": "Shwood Eyewear", "domain": "shwoodshop.com", "niche": "Fashion Accessories", "sub_niche": "Handcrafted Eyewear", "country": "United States", "employee_est": "1-10"},
    {"brand": "Finisterre Bags", "domain": "finisterre.com", "niche": "Fashion Accessories", "sub_niche": "Bags & Outdoor Gear", "country": "United Kingdom", "employee_est": "11-50"},
    {"brand": "Melin", "domain": "melin.com", "niche": "Fashion Accessories", "sub_niche": "Performance Hats & Caps", "country": "United States", "employee_est": "11-50"},
    {"brand": "Gaston Luga", "domain": "gastonluga.com", "niche": "Fashion Accessories", "sub_niche": "Scandinavian Backpacks", "country": "Sweden", "employee_est": "11-50"},
    {"brand": "Kapten & Son", "domain": "kapten-son.com", "niche": "Fashion Accessories", "sub_niche": "Watches & Backpacks", "country": "Germany", "employee_est": "51-100"},
    {"brand": "Ekster", "domain": "ekster.com", "niche": "Fashion Accessories", "sub_niche": "Smart Wallets", "country": "Netherlands", "employee_est": "11-50"},
    {"brand": "Anson Belt & Buckle", "domain": "ansonbelt.com", "niche": "Fashion Accessories", "sub_niche": "Holeless Belts", "country": "United States", "employee_est": "1-10"},
    {"brand": "Mission Belt", "domain": "missionbelt.com", "niche": "Fashion Accessories", "sub_niche": "Ratcheting Belts", "country": "United States", "employee_est": "1-10"},
    {"brand": "Vincero Collective", "domain": "vincerocollective.com", "niche": "Fashion Accessories", "sub_niche": "Watches & Eyewear", "country": "United States", "employee_est": "11-50"},
    {"brand": "RAEN Optics", "domain": "raen.com", "niche": "Fashion Accessories", "sub_niche": "Handmade Eyewear", "country": "United States", "employee_est": "11-50"},

    # --- JEWELRY: Chains, Rings, Lab-Grown Diamonds, Custom, Men's Jewelry ---
    {"brand": "Mejuri", "domain": "mejuri.com", "niche": "Jewelry", "sub_niche": "Fine Jewelry", "country": "Canada", "employee_est": "51-100"},
    {"brand": "CRAFTD London", "domain": "craftdlondon.com", "niche": "Jewelry", "sub_niche": "Men's Chains & Pendants", "country": "United Kingdom", "employee_est": "11-50"},
    {"brand": "GLD Shop", "domain": "thegldshop.com", "niche": "Jewelry", "sub_niche": "Urban Jewelry & Chains", "country": "United States", "employee_est": "11-50"},
    {"brand": "Missoma", "domain": "missoma.com", "niche": "Jewelry", "sub_niche": "Demi-Fine Jewelry", "country": "United Kingdom", "employee_est": "51-100"},
    {"brand": "Vitaly", "domain": "vitalydesign.com", "niche": "Jewelry", "sub_niche": "Recycled Steel Jewelry", "country": "Canada", "employee_est": "11-50"},
    {"brand": "Jaxxon", "domain": "jaxxon.com", "niche": "Jewelry", "sub_niche": "Men's Italian Gold Chains", "country": "United States", "employee_est": "11-50"},
    {"brand": "Astrid & Miyu", "domain": "astridandmiyu.com", "niche": "Jewelry", "sub_niche": "Earrings & Piercings", "country": "United Kingdom", "employee_est": "51-100"},
    {"brand": "Monica Vinader", "domain": "monicavinader.com", "niche": "Jewelry", "sub_niche": "Sustainable Everyday Luxury", "country": "United Kingdom", "employee_est": "51-100"},
    {"brand": "Catbird", "domain": "catbirdnyc.com", "niche": "Jewelry", "sub_niche": "Ethical Gold & Rings", "country": "United States", "employee_est": "51-100"},
    {"brand": "Brilliant Earth", "domain": "brilliantearth.com", "niche": "Jewelry", "sub_niche": "Ethical & Lab Diamonds", "country": "United States", "employee_est": "51-100"},
    {"brand": "Aurate New York", "domain": "auratenewyork.com", "niche": "Jewelry", "sub_niche": "Direct Fine Jewelry", "country": "United States", "employee_est": "11-50"},
    {"brand": "Kimaï", "domain": "kimai.com", "niche": "Jewelry", "sub_niche": "Lab-Grown Diamonds", "country": "United Kingdom", "employee_est": "1-10"},
    {"brand": "Miansai", "domain": "miansai.com", "niche": "Jewelry", "sub_niche": "Handcrafted Men's & Women's", "country": "United States", "employee_est": "11-50"},
    {"brand": "Clocks and Colours", "domain": "clocksandcolours.com", "niche": "Jewelry", "sub_niche": "Heavy Sterling Silver Men's", "country": "Canada", "employee_est": "1-10"},
    {"brand": "Linjer", "domain": "linjer.co", "niche": "Jewelry", "sub_niche": "Minimalist Fine Jewelry", "country": "United States", "employee_est": "1-10"},
    {"brand": "Daisy London", "domain": "daisyjewellery.com", "niche": "Jewelry", "sub_niche": "Everyday Gold & Silver", "country": "United Kingdom", "employee_est": "11-50"},
    {"brand": "Stone and Strand", "domain": "stoneandstrand.com", "niche": "Jewelry", "sub_niche": "Trendy Fine Jewelry", "country": "United States", "employee_est": "11-50"},
    {"brand": "Studs", "domain": "studs.com", "niche": "Jewelry", "sub_niche": "Earrings & Earscaping", "country": "United States", "employee_est": "51-100"},
    {"brand": "Ring Concierge", "domain": "ringconcierge.com", "niche": "Jewelry", "sub_niche": "Bespoke Bridal & Fine", "country": "United States", "employee_est": "11-50"},
    {"brand": "Local Eclectic", "domain": "localeclectic.com", "niche": "Jewelry", "sub_niche": "Independent Designer Jewelry", "country": "United States", "employee_est": "11-50"},

    # --- HEALTH & SUPPLEMENTS: Vitamins, Protein, Gut Health, Sleep, Pre-workout ---
    {"brand": "AG1 (Athletic Greens)", "domain": "drinkag1.com", "niche": "Health & Supplements", "sub_niche": "Comprehensive Daily Greens", "country": "United States", "employee_est": "51-100"},
    {"brand": "Ritual", "domain": "ritual.com", "niche": "Health & Supplements", "sub_niche": "Traceable Multivitamins", "country": "United States", "employee_est": "51-100"},
    {"brand": "Seed Health", "domain": "seed.com", "niche": "Health & Supplements", "sub_niche": "Synbiotics & Gut Health", "country": "United States", "employee_est": "51-100"},
    {"brand": "Huel", "domain": "huel.com", "niche": "Health & Supplements", "sub_niche": "Nutritionally Complete Food", "country": "United Kingdom", "employee_est": "51-100"},
    {"brand": "Liquid I.V.", "domain": "liquid-iv.com", "niche": "Health & Supplements", "sub_niche": "Hydration Multiplier", "country": "United States", "employee_est": "51-100"},
    {"brand": "Care/of", "domain": "takecareof.com", "niche": "Health & Supplements", "sub_niche": "Personalized Vitamin Packs", "country": "United States", "employee_est": "11-50"},
    {"brand": "Moon Juice", "domain": "moonjuice.com", "niche": "Health & Supplements", "sub_niche": "Adaptogens & Brain Health", "country": "United States", "employee_est": "11-50"},
    {"brand": "Four Sigmatic", "domain": "foursigmatic.com", "niche": "Health & Supplements", "sub_niche": "Functional Mushroom Coffee", "country": "United States", "employee_est": "11-50"},
    {"brand": "Mud/Wtr", "domain": "mudwtr.com", "niche": "Health & Supplements", "sub_niche": "Coffee Alternatives & Focus", "country": "United States", "employee_est": "11-50"},
    {"brand": "HUM Nutrition", "domain": "humnutrition.com", "niche": "Health & Supplements", "sub_niche": "Beauty & Wellness Vitamins", "country": "United States", "employee_est": "51-100"},
    {"brand": "Heights", "domain": "yourheights.com", "niche": "Health & Supplements", "sub_niche": "Brain Care & Vitals", "country": "United Kingdom", "employee_est": "11-50"},
    {"brand": "MaryRuth Organics", "domain": "maryruthorganics.com", "niche": "Health & Supplements", "sub_niche": "Liquid Multivitamins", "country": "United States", "employee_est": "51-100"},
    {"brand": "Gainful", "domain": "gainful.com", "niche": "Health & Supplements", "sub_niche": "Custom Protein Powder", "country": "United States", "employee_est": "11-50"},
    {"brand": "Beam", "domain": "shopbeam.com", "niche": "Health & Supplements", "sub_niche": "Sleep & Recovery", "country": "United States", "employee_est": "11-50"},
    {"brand": "Equip Foods", "domain": "equipfoods.com", "niche": "Health & Supplements", "sub_niche": "Beef Protein & Whole Foods", "country": "United States", "employee_est": "1-10"},
    {"brand": "Transparent Labs", "domain": "transparentlabs.com", "niche": "Health & Supplements", "sub_niche": "Clean Pre-Workout & Protein", "country": "United States", "employee_est": "11-50"},
    {"brand": "Ghost Lifestyle", "domain": "ghostlifestyle.com", "niche": "Health & Supplements", "sub_niche": "Lifestyle Sports Nutrition", "country": "United States", "employee_est": "11-50"},
    {"brand": "Bare Performance Nutrition", "domain": "bareperformancenutrition.com", "niche": "Health & Supplements", "sub_niche": "Endurance & Fitness", "country": "United States", "employee_est": "11-50"},
    {"brand": "KOS", "domain": "kos.com", "niche": "Health & Supplements", "sub_niche": "Organic Plant Protein", "country": "United States", "employee_est": "11-50"},
    {"brand": "ARMRA", "domain": "tryarmra.com", "niche": "Health & Supplements", "sub_niche": "Bovine Colostrum & Immunity", "country": "United States", "employee_est": "11-50"},
    {"brand": "Clevr Blends", "domain": "clevrblends.com", "niche": "Health & Supplements", "sub_niche": "Superlatte & Adaptogens", "country": "United States", "employee_est": "11-50"},
    {"brand": "WelleCo", "domain": "welleco.com", "niche": "Health & Supplements", "sub_niche": "Plant-based Elixirs", "country": "Australia", "employee_est": "11-50"},
    {"brand": "Troop Mushrooms", "domain": "trytroop.com", "niche": "Health & Supplements", "sub_niche": "Mushroom Gummies", "country": "United States", "employee_est": "1-10"},

    # --- EXTENDED DTC: Skincare, Grooming, Pets, Home & Candles ---
    {"brand": "Dr. Squatch", "domain": "drsquatch.com", "niche": "Extended DTC", "sub_niche": "Natural Men's Grooming", "country": "United States", "employee_est": "51-100"},
    {"brand": "Harry's", "domain": "harrys.com", "niche": "Extended DTC", "sub_niche": "Men's Shaving & Care", "country": "United States", "employee_est": "51-100"},
    {"brand": "Lumin Skin", "domain": "luminskin.com", "niche": "Extended DTC", "sub_niche": "Men's Skincare", "country": "United States", "employee_est": "11-50"},
    {"brand": "Disco Skincare", "domain": "letsdisco.com", "niche": "Extended DTC", "sub_niche": "Clean Men's Skincare", "country": "United States", "employee_est": "1-10"},
    {"brand": "Supply Co", "domain": "supply.co", "niche": "Extended DTC", "sub_niche": "Single Edge Razors", "country": "United States", "employee_est": "1-10"},
    {"brand": "Dieux Skin", "domain": "dieuxskin.com", "niche": "Extended DTC", "sub_niche": "Clinical Skincare", "country": "United States", "employee_est": "1-10"},
    {"brand": "Topicals", "domain": "mytopicals.com", "niche": "Extended DTC", "sub_niche": "Skin Health & Hyper-pigmentation", "country": "United States", "employee_est": "11-50"},
    {"brand": "Tower 28 Beauty", "domain": "tower28beauty.com", "niche": "Extended DTC", "sub_niche": "Sensitive Skin Cosmetics", "country": "United States", "employee_est": "11-50"},
    {"brand": "Ilia Beauty", "domain": "iliabeauty.com", "niche": "Extended DTC", "sub_niche": "Clean Color Cosmetics", "country": "United States", "employee_est": "51-100"},
    {"brand": "Wild Deodorant", "domain": "wearewild.com", "niche": "Extended DTC", "sub_niche": "Refillable Natural Deodorant", "country": "United Kingdom", "employee_est": "11-50"},
    {"brand": "Fussy Deodorant", "domain": "getfussy.com", "niche": "Extended DTC", "sub_niche": "Sustainable Deodorant", "country": "United Kingdom", "employee_est": "1-10"},
    {"brand": "BarkBox", "domain": "barkbox.com", "niche": "Extended DTC", "sub_niche": "Pet Toys & Treats", "country": "United States", "employee_est": "51-100"},
    {"brand": "Wild One", "domain": "wildone.com", "niche": "Extended DTC", "sub_niche": "Modern Dog Essentials", "country": "United States", "employee_est": "11-50"},
    {"brand": "Fable Pets", "domain": "fablepets.com", "niche": "Extended DTC", "sub_niche": "Ergonomic Pet Gear", "country": "United States", "employee_est": "11-50"},
    {"brand": "Our Place", "domain": "fromourplace.com", "niche": "Extended DTC", "sub_niche": "Modern Cookware", "country": "United States", "employee_est": "51-100"},
    {"brand": "Caraway Home", "domain": "carawayhome.com", "niche": "Extended DTC", "sub_niche": "Non-Toxic Cookware", "country": "United States", "employee_est": "51-100"},
    {"brand": "Great Jones", "domain": "greatjonesgoods.com", "niche": "Extended DTC", "sub_niche": "Color Cookware", "country": "United States", "employee_est": "11-50"},
    {"brand": "Material Kitchen", "domain": "materialkitchen.com", "niche": "Extended DTC", "sub_niche": "Minimalist Kitchenware", "country": "United States", "employee_est": "1-10"},
    {"brand": "Boy Smells", "domain": "boysmells.com", "niche": "Extended DTC", "sub_niche": "Candles & Fragrance", "country": "United States", "employee_est": "11-50"},
    {"brand": "P.F. Candle Co.", "domain": "pfcandleco.com", "niche": "Extended DTC", "sub_niche": "Home Fragrance & Amber Jars", "country": "United States", "employee_est": "11-50"},
    {"brand": "Brooklinen", "domain": "brooklinen.com", "niche": "Extended DTC", "sub_niche": "Bedding & Home Goods", "country": "United States", "employee_est": "51-100"},
    {"brand": "Parachute Home", "domain": "parachutehome.com", "niche": "Extended DTC", "sub_niche": "Premium Linens & Bedding", "country": "United States", "employee_est": "51-100"}
]

def get_all_target_brands():
    return TARGET_BRANDS
